/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.applicationproperty.view;

import com.mycompany.applicationproperty.ApplicationProperty;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mamir
 */
public class CustomerHomeView extends javax.swing.JPanel {

    /**
     * Creates new form HomePageView
     */
    private ApplicationProperty app;
    private int userId;
    private int userType;
    private int type = 0;
    private int idOwner = 0;
    private int idItem = 0;

    public CustomerHomeView(ApplicationProperty app) {
        initComponents();
        this.app = app;
        userId = app.currentUser;
        userType = app.currentType;
        String name = "Hello, " + app.store.getCustomer(userId).
                getFullName();

        labelWelcome.setText(name);
        
        viewBalance();
        
        inputId.setEditable(false);
        inputOwner.setEditable(false);
        inputCost.setEditable(false);
        inputLocation.setEditable(false);
        inputBuildingArea.setEditable(false);
        inputManyRooms.setEditable(false);

        DataView();
    }

    private void viewBalance() {
        String balance = "$USD " + Integer.toString(app.store.
                getCustomer(userId).getTabungan().getSaldo());
        label_balance.setText(balance);

    }

    private void clear() {
        inputId.setText("");
        inputOwner.setText("");
        inputCost.setText("");
        inputLocation.setText("");
        inputBuildingArea.setText("");
        inputManyRooms.setText("");
    }

    private void DataView() {
        DefaultTableModel model = new DefaultTableModel();
        userId = app.currentUser;
        if (type == 0) {
            model.addColumn("Code Item");
            model.addColumn("Owner");
            model.addColumn("Cost");
            model.addColumn("Location");

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            if (app.store.getAmountSeller() > 0) {
                for (int i = 0; i < app.store.getAmountSeller(); i++) {
                    if (app.store.getSeller(i).getAmountHouse() > 0) {
                        for (int j = 0; j < app.store.getSeller(i).getAmountHouse(); j++) {
                            if (app.store.getSeller(i).getHouseByIdx(j).getAvailable() == true) {

                                Object[] data = {
                                    app.store.getSeller(i).getHouseByIdx(j).getCode(),
                                    app.store.getSeller(i).getUserName(),
                                    app.store.getSeller(i).getHouseByIdx(j).getCost(),
                                    app.store.getSeller(i).getHouseByIdx(j).getLocation(),};
                                model.addRow(data);
                            }
                        }
                    }
                }
            }
        } else {
            model.addColumn("Code Item");
            model.addColumn("Owner");
            model.addColumn("Cost");
            model.addColumn("Location");

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            if (app.store.getAmountSeller() > 0) {
                for (int i = 0; i < app.store.getAmountSeller(); i++) {
                    if (app.store.getSeller(i).getAmountLand() > 0) {
                        for (int j = 0; j < app.store.getSeller(i).getAmountLand(); j++) {
                            if (app.store.getSeller(i).getLandByIdx(j).getAvailable() == true) {
                                Object[] data = {
                                    app.store.getSeller(i).getLandByIdx(j).getCode(),
                                    app.store.getSeller(i).getUserName(),
                                    app.store.getSeller(i).getLandByIdx(j).getCost(),
                                    app.store.getSeller(i).getLandByIdx(j).getLocation(),};
                                model.addRow(data);
                            }
                        }
                    }

                }
            }
        }

        tblOutput.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        btnWithDraw = new javax.swing.JButton();
        labelWelcome = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_balance = new javax.swing.JLabel();
        btnTopUp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOutput = new javax.swing.JTable();
        btnHouse = new javax.swing.JButton();
        btnLand = new javax.swing.JButton();
        btnMyPurchase = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputCost = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        lblManyRooms = new javax.swing.JLabel();
        inputBuildingArea = new javax.swing.JTextField();
        inputManyRooms = new javax.swing.JTextField();
        btnBuy = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        inputLocation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        inputOwner = new javax.swing.JTextField();

        jButton5.setText("jButton5");

        btnWithDraw.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnWithDraw.setText("Withdraw");
        btnWithDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithDrawActionPerformed(evt);
            }
        });

        labelWelcome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelWelcome.setText("Hello, (name), Welcome Back");

        btnLogOut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Your Balance :");

        label_balance.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        label_balance.setForeground(new java.awt.Color(51, 51, 51));
        label_balance.setText("Rp.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(label_balance))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_balance)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTopUp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTopUp.setText("Top Up");
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("All Property Sales");

        tblOutput.setBackground(new java.awt.Color(229, 239, 193));
        tblOutput.setForeground(new java.awt.Color(0, 0, 0));
        tblOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "First Name", "Last Name", "Balance", "User Name", "Password"
            }
        ));
        tblOutput.setGridColor(new java.awt.Color(0, 0, 0));
        tblOutput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOutputMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblOutput);

        btnHouse.setText("House");
        btnHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHouseActionPerformed(evt);
            }
        });

        btnLand.setText("Land");
        btnLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLandActionPerformed(evt);
            }
        });

        btnMyPurchase.setText("My Purchases");
        btnMyPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyPurchaseActionPerformed(evt);
            }
        });

        jLabel3.setText("Detail Property");

        jLabel4.setText("Cost");

        lblArea.setText("Building Area");

        lblManyRooms.setText("Many Rooms");

        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        jLabel9.setText("Location");

        jLabel10.setText("Owner");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel11.setText("ID Product");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(371, 371, 371)
                .addComponent(btnMyPurchase)
                .addGap(62, 62, 62))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHouse)
                        .addGap(8, 8, 8)
                        .addComponent(btnLand)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(btnCancel)
                                    .addGap(28, 28, 28))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inputOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inputCost, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inputLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblArea)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inputBuildingArea, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblManyRooms)
                                            .addGap(38, 38, 38)
                                            .addComponent(inputManyRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(11, 11, 11)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnBuy)
                                .addGap(153, 153, 153))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLand)
                            .addComponent(btnHouse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(inputOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(inputLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputBuildingArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManyRooms)
                            .addComponent(inputManyRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnBuy)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(btnTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnWithDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(357, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnLogOut)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWithDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnWithDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithDrawActionPerformed
        app.showWithdrawView();
    }//GEN-LAST:event_btnWithDrawActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        app.currentUser = -1;
        app.currentType = -1;
        app.showLoginView();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpActionPerformed
        app.showTopUpView();
    }//GEN-LAST:event_btnTopUpActionPerformed

    private void tblOutputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOutputMouseClicked
        // TODO add your handling code here
        if (type == 0) {
            inputId.setText(tblOutput.getValueAt(tblOutput.
                    getSelectedRow(), 0).toString());
            inputOwner.setText(tblOutput.getValueAt(tblOutput.
                    getSelectedRow(), 1).toString());

            try {
                idItem = app.store.findHouse(Integer.parseInt(
                        inputId.getText()));
                idOwner = app.store.getIndexCustomerAndSeller(
                        inputOwner.getText());
                inputCost.setText(Integer.toString(app.store.
                        getSeller(idOwner).getHouseByIdx(idItem).
                        getCost()));
                inputCost.setText(Integer.toString(app.store.
                        getSeller(idOwner).getHouseByIdx(idItem).
                        getCost()));
                inputLocation.setText(app.store.
                        getSeller(idOwner).getHouseByIdx(idItem).
                        getLocation());
                inputBuildingArea.setText(Integer.toString(app.store.
                        getSeller(idOwner).getHouseByIdx(idItem).
                        getBuildingArea()));
                inputManyRooms.setText(Integer.toString(app.store.
                        getSeller(idOwner).getHouseByIdx(idItem).
                        getManyRooms()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Can't find "
                        + "id Item or id Owner");
            }

        } else {
            inputId.setText(tblOutput.getValueAt(tblOutput.
                    getSelectedRow(), 0).toString());
            inputOwner.setText(tblOutput.getValueAt(tblOutput.
                    getSelectedRow(), 1).toString());

            try {
                idItem = app.store.findLand(Integer.parseInt(
                        inputId.getText()));
                idOwner = app.store.getIndexCustomerAndSeller(
                        inputOwner.getText());
                inputCost.setText(Integer.toString(app.store.
                        getSeller(idOwner).getLandByIdx(idItem).
                        getCost()));
                inputCost.setText(Integer.toString(app.store.
                        getSeller(idOwner).getLandByIdx(idItem).
                        getCost()));
                inputLocation.setText(app.store.
                        getSeller(idOwner).getLandByIdx(idItem).
                        getLocation());
                inputBuildingArea.setText(Integer.toString(app.store.
                        getSeller(idOwner).getLandByIdx(idItem).
                        getLandArea()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Can't find "
                        + "id Item or id Owner");
            }
        }
    }//GEN-LAST:event_tblOutputMouseClicked

    private void btnHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHouseActionPerformed
        // TODO add your handling code here:
        clear();
        lblManyRooms.setText("Many Rooms");
        inputManyRooms.setVisible(true);
        lblArea.setText("Building Area");
        type = 0;
        DataView();
    }//GEN-LAST:event_btnHouseActionPerformed

    private void btnLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandActionPerformed
        // TODO add your handling code here:
        clear();
        lblManyRooms.setText("");
        lblArea.setText("Land Area");
        inputManyRooms.setVisible(false);
        type = 1;
        DataView();
    }//GEN-LAST:event_btnLandActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        if (type == 0) {
            int amountCost = Integer.parseInt(inputCost.getText());
            int idHouse = Integer.parseInt(inputId.getText());
            int buildArea = Integer.parseInt(inputBuildingArea.getText());
            int manyRooms = Integer.parseInt(inputManyRooms.getText());
            String location = inputLocation.getText();
            if (app.store.getCustomer(userId).getTabungan().
                    ambilUang(amountCost)) {
                app.store.getSeller(idOwner).deleteHouse(idItem);

                app.store.getSeller(idOwner).getTabungan()
                        .simpanUang(amountCost);

                app.store.getCustomer(userId).addHouse(idHouse,
                        buildArea, manyRooms, amountCost,
                        location);
                JOptionPane.showMessageDialog(this, "Withdraw"
                        + " Success!");

            } else {
                JOptionPane.showMessageDialog(this, "Failed! You dont "
                        + "have enough money");
            }

        } else {
            int amountCost = Integer.parseInt(inputCost.getText());
            int idLand = Integer.parseInt(inputId.getText());
            int landArea = Integer.parseInt(inputBuildingArea.getText());
            String location = inputLocation.getText();
            if (app.store.getCustomer(userId).getTabungan().
                    ambilUang(amountCost)) {
                app.store.getSeller(idOwner).getHouseByIdx(idItem).
                        setAvailable(false);
                app.store.getSeller(idOwner).getTabungan()
                        .simpanUang(amountCost);

                app.store.getCustomer(userId).addLand(idLand,
                        landArea, amountCost, location);
                JOptionPane.showMessageDialog(this, "Withdraw"
                        + " Success!");

            } else {
                JOptionPane.showMessageDialog(this, "Failed! You dont "
                        + "have enough money");
            }
        }
        DataView();
        viewBalance();
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnMyPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyPurchaseActionPerformed
        // TODO add your handling code here:
        app.showMyPurchasedView();
    }//GEN-LAST:event_btnMyPurchaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnHouse;
    private javax.swing.JButton btnLand;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMyPurchase;
    private javax.swing.JButton btnTopUp;
    private javax.swing.JButton btnWithDraw;
    private javax.swing.JTextField inputBuildingArea;
    private javax.swing.JTextField inputCost;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputLocation;
    private javax.swing.JTextField inputManyRooms;
    private javax.swing.JTextField inputOwner;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JLabel label_balance;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblManyRooms;
    private javax.swing.JTable tblOutput;
    // End of variables declaration//GEN-END:variables
}
